# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d908f19b1220dc6d25c981882b63f848dc1e904df331cfed86350663ab0d2981060529c0e9cd550fe73c09751dc3ae777667ceac8aedb0335e36fc13f8aee4a8

test:
  secret_key_base: b5abb96feda344d66f0a65a596085aef66933d4bca7b827cae002815b7251ff178445da42adf5239dc271c1928814941a4add65bee4533d0e14077fdeaa1df49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
